### ISSUE TITLE
Problem: Missing Auth0 Integration Tutorial

### ISSUE THREAD

**Issue by mbalex99** [getditto/docs#106]
# Problem

Auth0 is a very popular authentication and identity management service. A lot of customers would love to see a well-written tutorial to help them integrate Ditto into an existing Auth0 backed application:

We need an example where an iOS, React, and Android device can log in with Auth0 and simultaneously get credentials to sync with Ditto. 

# Commentary

This tutorial should not include _how_ to set up an Auth0 application (this is too time-consuming to write). Assume that the user has _already_ integrated Auth0 into their iOS, React, or Android application. Just show the user how to integrate the Ditto Cloud portion.

Ideally this 

- [x] Please show how to login to Auth0 and also trigger a Ditto login with an Auth0 token
- [x] Please show how the auth webhook should be written. Please use a standard express API (NodeJS Express to be clear)
- [x] Explain how to logout of Auth0 and Ditto 
- [ ] Explain how to refresh the Ditto authentication

**Comment by okdistribute** [comment]
I see this Auth0 tutorial could also just come after the last page of 'Security With Authentication' -- let's see how it looks there.
