### ISSUE TITLE
Attachment use is sort of confusing to find

### ISSUE THREAD

**Issue by bigfish24** [getditto/docs#11]
Personally, I find it confusing to think of going to Data Model to find the attachment APIs. It seems like it should also be referenced in `Insert, Update, Remove`

Thoughts?

**Comment by mbalex99** [comment]
It's definitely going to have its own section.

**Comment by okdistribute** [comment]
Agree. Thought about this a bit -- might be nice to have a 'Types' page once we get explicit types to group all of the types including Attachments together in one spot.
