### ISSUE TITLE
⬆️ Upgrade Docusaurus to 2.0.0-beta.15

### ISSUE THREAD

**Issue by phatblat** [getditto/docs#124]
![Screen Shot 2022-02-11 at 12 28 30 PM](https://user-images.githubusercontent.com/28851/153657001-4e4f6be5-91c1-4d0e-a4e1-fda24b9fc33b.png)

I have a little bit of this migration started in the [docusaurus-2b15](https://github.com/getditto/docs/commits/ben/docusaurus-2b15) branch. There were some breaking API changes so this will require more thorough testing.

**Comment by contenuto** [comment]
NA
