### ISSUE TITLE
Unclear "Tasks Tutorial" Page

### ISSUE THREAD

**Issue by bigfish24** [getditto/docs#13]
Should this be removed since it is empty? https://docs.ditto.live/tutorials/tasks/index

**Comment by mbalex99** [comment]
The index.md is now fixed, put to the top and filled with content and an image.

**Comment by mbalex99** [comment]
![image](https://user-images.githubusercontent.com/2183729/132396767-1cb2e24f-e0ce-468a-94fe-37ec3e5cf346.png)
 See
