### ISSUE TITLE
Problem: There's no search feature

### ISSUE THREAD

**Issue by kndoshn** [getditto/docs#138]
[Algolia DocSearch](https://docusaurus.io/docs/search) should be free to use since this is an open-source project.

**Comment by mbalex99** [comment]
I didn't have any luck on getting it to work! Any help would be good

**Comment by okdistribute** [comment]
Do we have an instance of DocSearch deployed somewhere? It says it is free only for open source projects, and you have to get approved https://docsearch.algolia.com/apply/

**Comment by kndoshn** [comment]
I've applied to the program last week and waiting for their response now.
