### ISSUE TITLE
GA page tracking is sending in the wrong page titles

### ISSUE THREAD

**Issue by joaquindk** [getditto/docs#141]
The GTM/GA plugin Is sending in the wrong page title each time a new page view is navigated to, as demonstrated using the Google Chrome GA plugin:

In the following screenshot the `/concepts/data-model` path is being visited, however it's page title (Data Model | Ditto) isn't being sent in, and instead we can see how the event contains `dt: Overview | Ditto`.

![image](https://user-images.githubusercontent.com/6567408/157387701-482698b8-f1fb-47e6-a550-ec752392cdbf.png)

Similar issues have been experienced by others before as documented on https://support.google.com/tagmanager/thread/56340317/incorrect-page-title-for-pageviews-sent-using-history-listener?hl=en

**Comment by contenuto** [comment]
NA
