### ISSUE TITLE
Problem: Out of date Linux setup instructions for BLE

### ISSUE THREAD

**Issue by mbalex99** [getditto/docs#15]
# Problem

The Linux BLE configuration seems like it's out of date given the latest updates.

# Solution

Please help update the documentation to the latest instructions that we know will work for most Linux distros including Raspian? 

1. The documentation link is here: https://docs.ditto.live/installation/linux/
2. Go to the bottom and click "Edit this Page"

![image](https://user-images.githubusercontent.com/2183729/132397227-5f2adbd8-439b-41df-a535-2f1b63f64eea.png)

**Comment by bigfish24** [comment]
Fixed with https://github.com/getditto/docs/commit/84fdd6f8c3998cd47ff05ee27362e0f0a9b2de4c and https://github.com/getditto/docs/commit/4da955822df66b5c542c952bb3b978627c55a4d8
