### ISSUE TITLE
Problem: Documentation is missing information about playground token

### ISSUE THREAD

**Issue by mbalex99** [getditto/docs#153]
# Problem

The portal has information about a playground token. However, there's nothing in the documentation that discusses this playground token. 

# Solution

- [ ] All installation code snippets should now include the playground token
- [ ] The tutorials apps should also make this available.

**Comment by okdistribute** [comment]
There is a PR for this from @konstantinbe to update the snippets to use playgroundv2

**Comment by konstantinbe** [comment]
@okdistribute you probably mean this one? https://github.com/getditto/ditto/pull/5318

Took a bit to convince CI but it's merged now. @mbalex99 should be OK now so we can close this issue?
