### ISSUE TITLE
Big Peer Internals images don't display well on dark mode

### ISSUE THREAD

**Issue by bigfish24** [getditto/docs#16]
https://docs.ditto.live/advanced/architecture/index

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/1036685/132398640-57894500-1758-4c5c-8bdb-7182ae1a878a.png">

**Comment by mbalex99** [comment]
Fixed on master:

<img width="1394" alt="Screen Shot 2021-09-07 at 2 20 52 PM" src="https://user-images.githubusercontent.com/2183729/132412482-8389412c-46a6-48eb-a747-8ac4efd58ec1.png">
