### ISSUE TITLE
Deprecate Cocoapods

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#171]
All places we mention cocoapods, we instead should mention Swift Package Manager.

For example, https://docs.ditto.live/tutorials/tasks/swiftui/setup#1-2-add-dependencies-cocoapods

We can keep the cocoapods reference around somewhere and link to it as part of the [Installation/ios page](https://docs.ditto.live/installation/ios)

**Comment by phatblat** [comment]
IMHO, CocoaPods will be around for a decent amount of time, but SwiftPM is certainly the "preferred" dependency manager by most iOS devs. One of the main reasons for this is that it is part of Xcode. However, there are a lot of projects out there using CocoaPods and not all libraries support SwiftPM yet.

**Comment by okdistribute** [comment]
Great, we should still probably call out both or just point to the installation page -- in the portal and tutorial pages we don't even mention SwiftPM and it looks like we don't support it unless you go sperlunking
