### ISSUE TITLE
Broken image reference in Mesh Network page

### ISSUE THREAD

**Issue by joe-trellick** [getditto/docs#22]
In the [Mesh Network](https://docs.ditto.live/advanced/architecture/mesh-network) page of the documentation, there's a visibly broken image link under the "Making and Breaking Connections" heading. The [source](https://github.com/getditto/docs/blob/master/docs/advanced/architecture/mesh-network.md) references the following missing PNG:
```
    <img src="./diagram2_new_peer.png"/>
```

**Comment by mbalex99** [comment]
Thanks Joe! We're adding new images shortly!
