### ISSUE TITLE
FindByID is missing in docs

### ISSUE THREAD

**Issue by bigfish24** [getditto/docs#272]
The API takes in a DittoDocumentID or does it alias into types that are allowable for doc IDs. Alternatively can I query with `find("_id == XXX")`?

**Comment by okdistribute** [comment]
Yes you can do `find("_id == XXX")` but we should definitely provide more explicit examples for `findByID`

**Comment by okdistribute** [comment]
We should turn these into snippets in the ditto repository.

**Comment by contenuto** [comment]
NA
