### ISSUE TITLE
Transport Config Guide

### ISSUE THREAD

**Issue by bigfish24** [getditto/docs#274]
The API docs have varied coverage of this and it would help to have code snippets showing how to control the transports.

**Comment by okdistribute** [comment]
Did you mean this? https://docs.ditto.live/ios/common/mesh-network/manual

Did you have trouble finding that page? Do you think it should be in some other section of the docs?

**Comment by bigfish24** [comment]
Yeah but expanded I guess it’s missing more of the configs

**Comment by okdistribute** [comment]
- [ ] Connect only to Bluetooth/AWDL/LAN 
- [ ] `enableDittoCloudSync`

Also the cars app has a lot of configuration options in it
