### ISSUE TITLE
Xamarin tutorial fixes

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#289]
- [x] Update for v2 (use `StartSync`, use `DittoCounter()`)
- [x] Add instructions to get around same bug we see in the Inventory app "Error while loading assemblies: /Users/rae/.nuget/packages/ditto/2.0.1/runtimes/win/native/dittoffi.dll. (MT0009) (Tasks)" We must be missing a step in the tutorial. Or maybe fixing this is obvious to C# users and I'm a n00b, but we should try to give best step-by-step instructions we can, so that anyone can get started.

Additional context: 
Still had issue #2 even if the following snippet is in the csproj file:

```
  <PropertyGroup>
    <RuntimeIdentifiers>win</RuntimeIdentifiers>
  </PropertyGroup>
```

**Comment by phatblat** [comment]
VS for Mac 2019 used to give an error until we added that to the project, but VS for Mac 2022 generates the following error.

> MTOUCH: Error MT0009: Error while loading assemblies: /Users/phatblat/.nuget/packages/ditto/2.0.1/runtimes/win/native/dittoffi.dll. (MT0009) (Inventory)

I found the following fix on a [xamarin issue thread](https://github.com/xamarin/xamarin-macios/issues/5265#issuecomment-506247673).

```xml
<RuntimeIdentifier>osx</RuntimeIdentifier>
<NuGetRuntimeIdentifier>osx</NuGetRuntimeIdentifier>
```

**Comment by okdistribute** [comment]
Thank you!
