### ISSUE TITLE
Add datetime as a type

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#310]
Advise ISO8601 strings for DateTime in Ditto. They're built natively into every framework on iOS, Android, .NET, and Web Browser. They're human readable, granular, and comparable (sortable)

Show examples for upsert, querying etc.

**Comment by okdistribute** [comment]
Use this snippet for swift: https://gist.github.com/magicwave/070c5c65ed05fea744cf604a33d6a6c4

**Comment by contenuto** [comment]
Confirmed in Best Practices >  Timestamp Values article currently in review: https://acrobat.adobe.com/id/urn:aaid:sc:va6c2:09df5bdb-2501-4e45-85fa-ae34d8e10d65
