### ISSUE TITLE
Add eviction to tutorials

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#313]
Add eviction pattern to each tutorial, to evict Todos after they have been deleted

- [x] Android
- [x] iOS
- [x] C#

See https://github.com/getditto/docs/pull/311

**Comment by okdistribute** [comment]
@texasRanger09 would you mind also adding this to the tutorials on the docs website?

**Comment by texasRanger09** [comment]
I added it to each of the docs as I updated the apps

**Comment by okdistribute** [comment]
Ahhh I see you committed directly to main. Got it.

If you commit directly to main on the docs for small things it is okay, but if you do that in general on github it's best practice to link to that hash commit in the issue so we have a record for the future project collaborators

https://github.com/getditto/docs/commit/3bacccdcfee69c4c51f72d14858dcac16a3e0783
