### ISSUE TITLE
Occasional mixing of other language's code/terminology in Rust docs

### ISSUE THREAD

**Issue by mcginty** [getditto/docs#330]
Reading through the Rust SDK docs, it looks like maybe some pieces copied from other SDKs have some incorrect/irrelevant pieces for the Rust docs.

Example at https://docs.ditto.live/rust/common/concepts/syncing-data#sync: referencing `startSync()` instead of `start_sync()` in the text, as well as some mobile-specific documentation that seems like it isn't applicable (at least directly) to the Rust SDK.

Another small example: https://docs.ditto.live/rust/common/concepts/syncing-data#observe, referencing "setting the LiveObject to null" which in Rust would probably mean dropping the variable.

**Comment by okdistribute** [comment]
Thanks for reporting, fixed!
