### ISSUE TITLE
[Swift] Document why `ObservedObject` vs `StateObject` in QuickTips

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#337]
https://www.avanderlee.com/swiftui/stateobject-observedobject-differences/
https://www.donnywals.com/whats-the-difference-between-stateobject-and-observedobject/

~We should change this in the swift sample apps and the tutorial.~ EDIT: going to just write up a little bit about the difference and how we recommend using this with Ditto

**Comment by texasRanger09** [comment]
We initialize the observable object with parameters (a ditto instance). However, you can't interact with a stateObject within an initializer. 
There seems to be some debate on how to properly initialize a stateObject with parameters.
https://stackoverflow.com/questions/62635914/initialize-stateobject-with-a-parameter-in-swiftui

**Comment by okdistribute** [comment]
We're going to put this into a short Quick Tip on iOS
