### ISSUE TITLE
Broken link Ditto Data Model from HTTP Introduction

### ISSUE THREAD

**Issue by k-rus** [getditto/docs#362]
[Introduction page](https://docs.ditto.live/http/installation) has link to [Ditto Data Model](https://docs.ditto.live/concepts/overview), which leads to Page Not Found. I am not sure if it is the issue that:
1.  Should Overview pagebe present for all documentation page?
2. Or should Ditto Data Model point to [Documents](https://docs.ditto.live/http/common/concepts/documents) and not to Overview?

**Comment by okdistribute** [comment]
Great, thanks. Fixed this -- did #2
