### ISSUE TITLE
Remove 'XCTAssertNotNil(docID)' reference in swift snippets

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#376]

**Comment by phatblat** [comment]
Which page(s) does this appear on?

**Comment by phatblat** [comment]
I found it https://docs.ditto.live/ios/common/concepts/writing#creating-a-document

<img width="458" alt="Screenshot 2022-12-01 at 2 41 26 PM" src="https://user-images.githubusercontent.com/28851/205164895-4d54b738-ad2a-44b9-bc2e-50ebad8a601a.png">

**Comment by phatblat** [comment]
Adding a `//@ditto/snippet-ignore-next-line` comment to this 👆🏻
