### ISSUE TITLE
Issues with Algolia search

### ISSUE THREAD

**Issue by k-rus** [getditto/docs#380]
I tried to search for `querying` and I am given the following result:
<img width="1030" alt="Screenshot 2022-12-06 at 11 10 13" src="https://user-images.githubusercontent.com/1726044/205882394-e59ce00d-8206-4519-afb6-009b85a92e00.png">
Note that page `Querying`, which exist for each SDKs, is not in the list. Note also that I have option to click on `See all 31 results`. When I click it I get the following, i.e., none of 31 results:
<img width="1215" alt="Screenshot 2022-12-06 at 11 12 14" src="https://user-images.githubusercontent.com/1726044/205882842-4a2af511-14a5-4b17-a1d4-62a52a4ef482.png">

**Comment by okdistribute** [comment]
This looks like a docusaurus bug for the current version we are on

**Comment by contenuto** [comment]
NA
