### ISSUE TITLE
Code snippets on top page are old

### ISSUE THREAD

**Issue by kndoshn** [getditto/docs#401]
https://www.ditto.live/

<img width="707" alt="image" src="https://user-images.githubusercontent.com/26117257/209252726-09a8711a-3435-4eee-9ac5-3f1e47f89157.png">

**Comment by okdistribute** [comment]
@rratner If you need help updating these to the latest, feel free to reach out to anyone on the customer engineering team

**Comment by rratner** [comment]
@okdistribute I'm seeing this now. Anyone specific I should reach out to?

**Comment by okdistribute** [comment]
@kndoshn and @aaronleopold should be able to help

**Comment by rratner** [comment]
This has now been merged in on the main website. Thanks @aaronleopold
