### ISSUE TITLE
feat: Portal | Update Documentation for API Key management

### ISSUE THREAD

**Issue by P0st-N0-B1lls** [getditto/docs#410]
# Problem
The documentation in the Docs section of the Portal is not referencing accurate information about the API Keys.  

https://docs.ditto.live/http/installation#api-key

# Solution
Update existing documentation to match implementation

# Commentary (Optional)
Slack thread: https://dittolive.slack.com/archives/C03ECU30SQL/p1673302779133019

**Comment by okdistribute** [comment]
@kw7oe Do you have time to help me describe the security mechanism used for the HTTP API key?
