### ISSUE TITLE
Extend Hybrid Logical Clock documentation.

### ISSUE THREAD

**Issue by skylerjokiel** [getditto/docs#413]
Adam wrote a great outline about Hybrid Logical Clock and why we use it in Ditto. Let's add this to our existing HLC documentation. https://docs.ditto.live/javascript/common/how-it-works/crdt#hybrid-logical-clock

> Ditto is a distributed system where data changes occur across devices. This can be hard to reason about because changes can occur concurrently. In mathematics, this is described as a “partial order” meaning that not all the data change events have a “happened before” relationship with each other. If you use Git, you experience this when you create a branch. Any changes you make on the branch are related to the prior changes on that branch, but subsequent changes to the main branch are not directly related. It is possible to resolve a partial order into a “total order” where all events are related, but this involves then establishing “happened before” relationships across all changes. Again with Git, this occurs when you merge a branch back into the main branch - changes are merged into a total order either automatically or with manual resolution. In the same way, Ditto has functionality to track a partial order of all data change events that occur across devices and then an automatic mechanism to merge the events into a total order.
> 
> Each Ditto document includes a version vector. The replication system uses the version vector to capture local and observed edits from other peers. When a peer incorporates changes from other peers, the local peer can use the incoming remote peer’s version vectors to determine whether the changes are new or old. In other words, a peer can distinguish from other peer’s incoming version vectors if the incoming data has “happened before” or not. This is called a “logical clock”.
> If every change across devices happened after observing all other changes, a logical clock would be sufficient to track the total order of events. However, reality doesn’t work that nicely! Events will occur concurrently to each other across devices creating a partial order, so we must rely on something else beyond the logical clock to order concurrent events. We choose to rely on the physical timestamp of the change as recorded by the device it occurred on to order concurrent events.
> However, it’s essential to know that even quartz-crystal-based physical clocks can skew forwards or backward in time. Almost every device regularly attempts to synchronize with an NTP-synchronized clock server. But even then, the round trip time from the request to the server’s response adds additional variability. In addition, there are limitations to nature and physics that will never allow two measurements of physical time to align precisely. As a result, while we generally trust physical clocks, we also need to manage inevitable clock skew too.
> 
> A version vector utilizes a monotonically increasing counter. Traditionally, a physical timestamp can’t be used for the counter because it is not guaranteed to be monotonic. Instead we use a “hybrid logical clock” (HLC) within the version vector. A HLC is a 64-bit timestamp comprised of 48 bits of a physical timestamp and 16 bits of a monotonically increasing logical clock. The logical part ensures that it is always monotonically increasing. Even if the physical clock skews to the past, the next observation will be higher than the last one. In addition, timestamps from other devices are incorporated as events are exchanged, ensuring that clocks always move forward. The net result, is that clock skew becomes bounded.
> 
> As long as changes from other sites are observed before subsequent changes, we can track the total order independent of the physical timestamp. If the changes are concurrent and we have a partial order, then we order the changes based on the HLC value, which is formed in part by the physical timestamp from the device that created the change, creating a total order. If a user were to change their device’s clock, HLC guards against going in the past, since it must be monotonic. However, moving a device clock forward would allow that change to win over a concurrent change (assuming the other clock is still relatively synchronized). But subsequent changes after observing the skewed clock won’t necessary be affected because the HLC will “fast forward” by observing the skewed clock, and any new change will get a HLC value ahead of it. Thus the use of HLC provides protection against clock skew in reverse and also prevents skew into the future from rendering changes that are logically happening later from losing out.

**Comment by contenuto** [comment]
https://docs.ditto.live/sync-concepts#iOY9q
