### ISSUE TITLE
Doc says WriteTransaction is not supported by Java

### ISSUE THREAD

**Issue by kndoshn** [getditto/docs#435]
The [Writing page](https://docs.ditto.live/android/common/concepts/writing) says write transaction is not supported by the Java SDK, but according to Ham ([Slack](https://dittolive.slack.com/archives/CGDF7RN3C/p1674216857608409?thread_ts=1674214777.774809&cid=CGDF7RN3C)) it should be supported.

![image](https://user-images.githubusercontent.com/26117257/213694985-c5d7e9b8-2182-4285-a55c-c426868d1fd1.png)

**Comment by kndoshn** [comment]
Test code : https://github.com/getditto/ditto/blob/main/android/dittojava/src/test/shared/live/ditto/dittotests/JavaDittoStoreTests.java#L32-L187

**Comment by contenuto** [comment]
NA since DQL v.4.5 doc release
