### ISSUE TITLE
Add to FAQ: Device-Device vs. Device-Server

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#471]
> We were wondering if we can use both connectivity types (Device-Device and Device-Server-Device) at the same time. If we use both approaches at the same time (if that's possible), will it affect the performance of mobile apps?

Yes you can use Device-Device and Device-Server-Device simultaneously on mobile devices. However, web browsers do not support peer-to-peer transports. That means a web app will only be able to talk to the big peer over websockets.

It should not affect the performance of the android and angular apps. If you see any performance degradation, please let us know as soon as possible.

To enable all Peer-to-Peer transports, call `transportConfig.enablePeerToPeer()`. If you don't want to use all transports, you can also enable individual transports, here is an example: https://docs.ditto.live/common/mesh-network/manual

**Comment by contenuto** [comment]
Added to _Platform Manual_ > [Transports](https://docs.ditto.live/transports).
Added to [FAQs](https://docs.ditto.live/faq#lUwpM).
