### ISSUE TITLE
Deprecate Obj-C SDK

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#478]
* Add a deprecation notice on the docs website on the iOS installation page.
* After one month, remove ObjC links from iOS page
* Add "using Obj-C" Quick Tip
  * Ditto singleton manager class needs to conform NSObject and have @objcMembers.  [See Slack conversation.](https://dittolive.slack.com/archives/CGDF7RN3C/p1677549229010089?thread_ts=1677545556.387269&cid=CGDF7RN3C)

**Comment by kndoshn** [comment]
Here is an example project showing how people can use DittoSwift in Objective-C apps:
- https://github.com/getditto/example-swift-bridge-to-objectivec

We can add a reference to this repo when we add `"using Obj-C" Quick Tip`.
