### ISSUE TITLE
Android installation process updates

### ISSUE THREAD

**Issue by thombles** [getditto/docs#508]
Some notes via Leo:

> Some corrections for the Android documentation, https://docs.ditto.live/android/installation
>
> * In setup, step 2, it should have the `mavenCentral()` repo in `settings.gradle` (Thats' where Android Studio puts it by default) or either one
> * Need to update the Ditto version - it says `0.3.5` but needed to be `3.0.6`
> * For some reason I had to manually add ditto to dependencies via `Project Structure -> Dependencies` via GUI ?? for the IDE to recognise the library with syntax support
> * The line `val androidDependencies = DefaultAndroidDittoDependencies(context)` should be changed to `val androidDependencies = DefaultAndroidDittoDependencies(applicationContext)`

**Comment by abunur** [comment]
> Some notes via Leo:
> 
> > Some corrections for the Android documentation, https://docs.ditto.live/android/installation
> > 
> > * In setup, step 2, it should have the `mavenCentral()` repo in `settings.gradle` (Thats' where Android Studio puts it by default) or either one
> > * Need to update the Ditto version - it says `0.3.5` but needed to be `3.0.6`
> > * For some reason I had to manually add ditto to dependencies via `Project Structure -> Dependencies` via GUI ?? for the IDE to recognise the library with syntax support
> > * The line `val androidDependencies = DefaultAndroidDittoDependencies(context)` should be changed to `val androidDependencies = DefaultAndroidDittoDependencies(applicationContext)`

all of these have been completed with the exception of `context` -> `applicationContext`. That code snippet is being loaded from somewhere else, am trying to track it down.

cc @okdistribute

**Comment by abunur** [comment]
Think I found the relevant snippet; PR created
