### ISSUE TITLE
Bottom navigation is broken - always defaults to JavaScript

### ISSUE THREAD

**Issue by abunur** [getditto/docs#513]
The sidebar navigation for the docs defaults to JavaScript regardless of where the user is navigating from. For example, if the user is following an iOS tutorial, clicking the link at the bottom of a page to go to the next page, goes not the to the iOS version of the tutorial, but rather the Javascript version. Hence bottom navigation for all tutorials outside of Javascript is broken. The same issue occurs with Android and other flows.

**Comment by okdistribute** [comment]
I was not able to reproduce this.
