### ISSUE TITLE
in iOS 16 you may see bluetooth devices connected

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#521]
iOS devices are now connected via bluetooth to android devices in the iOS bluetooth settings module which is visible to the end-user. When you force close the app, the iOS devices disconnect their BT connection to the android devices. This is a security feature of iOS and is not indicative of any issue. There is no limitation on the number of bluetooth devices and it is purely for information.

**Comment by contenuto** [comment]
_Platform Manual_ > "Transports" > "Bluetooth Low Energy" > "[Limitations](https://docs.ditto.live/transports#M4qpw)"
