### ISSUE TITLE
Add explanation about OnlinePlayground auth every 7 Days

### ISSUE THREAD

**Issue by kndoshn** [getditto/docs#531]
- The doc does not seem to explain that devices using OnlinePlayground must be authenticated online every 7 days.

**Comment by kndoshn** [comment]
@okdistribute Is my understanding correct that OnlinePlayground's offline capability is 7 days? I remember seeing that somewhere but am not sure.

**Comment by okdistribute** [comment]
Here is the part where this is discussed: https://docs.ditto.live/ios/common/mesh-network/online-playground#going-offline

@contenuto is doing an overhaul of docs right now to improve readibility so hopefully this will improve
