### ISSUE TITLE
Add a docs page on Logging

### ISSUE THREAD

**Issue by skylerjokiel** [getditto/docs#544]
### Goal
Customers should understand the different log levels, when to use each, and how to set them. Customers should also be able to understand how to interpret any logs.

### Info

Customer facing log levels include:
- Info
- Debug
- Warning
- Error

Ditto specific log levels include:
- Trace

^^ As per https://dittolive.slack.com/archives/CJCFGTK9T/p1682378065599859?thread_ts=1682374934.119069&cid=CJCFGTK9T

Currently we have this logging information in our troubleshooting section. It's better than nothing but focuses on debugging read and write transactions as opposed to how to consume our logs holistically.
https://docs.ditto.live/common/troubleshooting#read-vs-write-transactions

**Comment by okdistribute** [comment]
Thanks Skyler. One small correction - the trace level is called verbose. We should discourage developers from using this log level.

**Comment by connorpower** [comment]
In our public SDK  the level is called `verbose` but internally in our codebase it's called `trace` - hence the confusion. `trace` is the term used by practically every logging tool - log4j, Kotlin logging, rust logs, tracing, swift log, etc...).

It's always bugged me a bit that our public SDK seems alone in its use of the term `verbose`. Perhaps it's too late to change now though.

**Comment by okdistribute** [comment]
* Authentication success & failure
* Big peer is visible
* Subscriptions that persist across the length of a session
* Permissions that do and do not overlap with subscriptions (read/write permissions)
* Bluetooth failure
