### ISSUE TITLE
Livequery/subscriptions are stopped when deallocated

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#557]
We want to clarify in the docs for live queries and subscription objects that they are stopped once they are deallocated, however this is asynchronous.

That means in Swift you need to wrap any `liveQuery =  nil` calls in an `autorelease` block, or they won’t nil till end of the parent function call.

This is worse in other languages that are garbage collected (e.g., Kotlin). 

We still recommend best practice for all platforms to use `stop()`, but this caveat could be interesting for non-GC languages such as Swift.

**Comment by contenuto** [comment]
NA
