### ISSUE TITLE
Broken links on http

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#558]
the link “[You can learn more about the supported transports and upcoming transports here](https://docs.ditto.live/http/common/mesh-network/supported-transports)” is broken on the public [Mesh Network](https://docs.ditto.live/http/common/how-it-works/mesh-network) docs page when your language is set to HTTP

**Comment by define-null** [comment]
Adding to this ticket, to collect more broken links. 

At the page: https://docs.ditto.live/http/common/concepts/querying following the link to "Next
Syncing »" at the bottom (https://docs.ditto.live/common/concepts/syncing-data) leads to "Page not found"

**Comment by contenuto** [comment]
NA
