### ISSUE TITLE
Make OnlinePlayground clear

### ISSUE THREAD

**Issue by skylerjokiel** [getditto/docs#630]
## Problem
Our Online Playground is a bit confusing because it's called Online Playground but it actually supports offline mode. Our docs state this indirectly and our Customer Engineering team has received questions about this.

## Solution
Improve the doc to more clearly state that this can be used offline.

## Link

https://docs.ditto.live/android/common/mesh-network/online-playground

**Comment by contenuto** [comment]
Created _Ditto Basics_ > "Authentication and Initialization" article: https://docs.ditto.live/basics/authentication-and-initialization
