### ISSUE TITLE
Use observeLocal instead of exec for the find query examples

### ISSUE THREAD

**Issue by contenuto** [getditto/docs#682]
Recreated from alpha docs repo: https://github.com/getditto/alphadocs/issues/34

Describe the issue

exec is discouraged because it is a blocking call that does not respond to changes on the local database. One of the most common support tickets we receive is related to using "Exec" instead of observeLocal, where they expect ditto to operate like HTTP and block until the data is retrieved.

To Reproduce
https://alphadocs.ditto.live/gFiO-find-and-observe#Ql1ng

Expected behavior

Instead the CRUD introduction would benefit from a simple example that shows how to upsert data and then listen to those changes as they happen. Right now it is difficult to understand how these are used in combination with each other.

The observeLocal call docs is at the bottom of the page which instead should be at the top, since it is the primary way that customers should use the database. This should be then re-used in conjunction with the rest of the code samples below it.

I'd also suggest that exec is given a small section at the end of the Find page, but with the clear caveats that it should only be used if absolutely necessary because it is a blocking call that will:

slow down your UI if used in the main thread
not be real-time
Screenshots
Provide a screenshots to help explain your problem.

Additional context

**Comment by contenuto** [comment]
Skyler says NA. 2024-01-09

**Comment by skylerjokiel** [comment]
If this is an issue again, feel free to raise it.
