### ISSUE TITLE
HTTP examples missing

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#693]
`/api/v4/store/write`
* `commands`: methods `remove`, `update`, `upsert`. The write command parameters change for each method.
* `valueTypeOverrides`: is optional, what does it do and what values are allowed?

HTTP API Reference > Endpoints is inaccurate

**Comment by contenuto** [comment]
[Refreshed ](https://www.notion.so/getditto/Complete-HTTP-API-03a46c44d9394bd98841cb1d6cfc016c)
