### ISSUE TITLE
Call Stop to cancel a live query

### ISSUE THREAD

**Issue by texasRanger09** [getditto/docs#694]
**Describe the issue**
We call Stop to cancel a liveQuery and we call Cancel to cancel a Subscription
The docs state that we call Cancel for cancelling a liveQuery

**To Reproduce**
1. Docs site link https://docs.ditto.live/finding-and-observing
2. Scroll down to Canceling a Live Query
3. See error

**Expected behavior**
Should use Stop to cancel a liveQuery

**Screenshots**
<img width="231" alt="Screenshot 2023-09-26 at 1 54 50 PM" src="https://github.com/getditto/alphadocs/assets/60948031/25031a42-4a11-4c2e-97d8-4d8d1afa434d">

**Additional context**

**Comment by texasRanger09** [comment]
I fixed the issue in Archbee. Waiting to be published.

**Comment by contenuto** [comment]
NA
