### ISSUE TITLE
Android onlinewithauthentication content is missing

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#701]
**Describe the issue**

There is Android/Kotlin content that is missing from this tutorial: https://docs.ditto.live/onlinewithauthentication#0KUYf
**To Reproduce**
1. https://docs.ditto.live/onlinewithauthentication#0KUYf
2. Scroll down to tutorial
3. You see snippets for JS and Swift but not Kotlin

**Expected behavior**

There should be snippets for Kotlin https://legacydocs.ditto.live/android/common/security/authentication

**Screenshots**
Provide a screenshots to help explain your problem.

**Additional context**

**Comment by contenuto** [comment]
Added 2024-09-09 https://docs.ditto.live/kotlin/task-app-quickstart
