### ISSUE TITLE
Update Requery-Required instructions

### ISSUE THREAD

**Issue by nicholastmosher** [getditto/docs#702]
**Describe the issue**

We need to update the docs describing the CDC "requery required" message. Up until now, the message has included a `documents` field which was misleading and incorrect (the field never should have existed). [This PR that will be merged soon](https://github.com/getditto/ditto/pull/10173) will be hardcoding this field to be an empty list from here on out, and the field should be considered deprecated.

**To Reproduce**
1. Docs site link https://docs.ditto.live/kafka-connector#EvKL4 (requery required section)

**Expected behavior**

When a user receives a "requery required" message, it means they need to requery the _full_ dataset, not just the list of documents in the requery-required message as was instructed before. If any customers were requerying only the documents in the `documents` list, they were being misled and certainly missing out on data updates.

**Screenshots**

![image](https://github.com/getditto/docs/assets/4210949/d9749632-e29b-48e5-a348-86acd53d0b77)

The `documents` field is being deprecated, the docs should pretend it doesn't exist or should inform users that it's deprecated and will no longer be anything but an empty list. Customers who were previously using this field should reach out to customer experience to tell us how they were attempting to use this field (because it means they were inadvertently being misled).

**Extra Context**

The problem with the `documents` field is that it simply did not do what the documentation said it did, and can inherently never be fixed to do that. If we have 10 transactions but "missed" 5 of them, we have no way of knowing which documents were edited in the 5 missed transactions, because they're gone, into the void, we have no idea what was in those transactions.

In reality, the system was populating the `documents` field with the list of documents that were edited in the first transaction _after_ the gap. So users were misled to believe that they could "requery" just the list of documents we provided them, but that would still leave them missing all of the changes from the 5 dropped transactions. The only way to recover and have a consistent view of the data after a "requery required" message is to requery the *_entire_ dataset, then resume applying changes from the CDC stream starting after the requery-required message.

\* by entire dataset, I actually mean the subset of data relevant to their CDC query. For example, if a user configured a webhook with a query of `order.amount < 10` (that might not be valid DQL, I'm not sure, but pretend it is), then they would only need to requery with the same query, so they'd only end up with the subset of orders under $10 (in this example), which should hopefully be much smaller than "the entire dataset" for most use-cases

**Comment by contenuto** [comment]
Added this warning:

The `documents` field is now deprecated and will only return an empty list. 

To maintain data integrity, if you receive a `requeryRequired` message, instead of using the `documents` field to query specific documents, requery the entire dataset. Requerying the complete dataset is crucial for avoiding the risk of missing data updates. 

After you've requeried the full dataset, directly following the requery-required message, resume applying changes from the CDC stream.
