### ISSUE TITLE
Creating registers using DittoRegister in all languages and HTTP API

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#707]
**What is the content you would like to see on Ditto's public docs? Please describe**
There is no overview of how to make a Map a Register on the docs using `DittoRegister` which is a constructor available in all languages.

**Describe why this content would help you using Ditto**

Some people want to use maps as registers because they want to update a document's field using a payload while deleting old values and rewriting the whole value in the map.

**Is this content language specific? (Yes/No/Unsure)**
no

**Provide any links to existing content or references that could help with writing this new content**

You can do this with upserts or updates on both the small peer and HTTP API. 

For HTTP, use valueTypeOverrides like below:
```
curl -X POST 'https://{app_id}.cloud.ditto.live/api/v4/store/write' \
  --header 'Content-Type: application/json' \
  --header 'Authorization: Bearer $API_KEY' \
  --data-raw '{
      "commands": [{
        "method": "upsert",
        "collection": "cars",
        "id": "123abc",
        "value": {
          "myRegister": value
        },
        "valueTypeOverrides": {
          "myRegister": "register"
        }
      }]
  }'
```

For the SDK:
```
val docId = ditto.store["cars"].upsert(
    mapOf(
        "_id" to "abc123",
        "myRegister" to DittoRegister(value)
    )
)
```

For SDK, using update, like so:
```
ditto.store.collection("cars").findById("abc123").update { mutableDoc ->
    mutableDoc?.let {
        it["myRegister"].set(DittoRegister(value))
    }
}
```

**Comment by contenuto** [comment]
NA
