### ISSUE TITLE
Sample repo is 404

### ISSUE THREAD

**Issue by kndoshn** [getditto/docs#716]
**Describe the issue**

[On the demo apps page](https://docs.ditto.live/demo-apps-overview),
the link should be now `https://github.com/getditto/samples`.

<img width="780" alt="samplelink-2" src="https://github.com/getditto/docs/assets/26117257/b466b7d4-a2e7-4eb8-8da0-33fab25cedee">

**Comment by contenuto** [comment]
Changed. https://docs.ditto.live/demo-apps-overview
