### ISSUE TITLE
Inaccurate information about supported versions of Node.js

### ISSUE THREAD

**Issue by pvditto** [getditto/docs#723]
**Describe the issue**
The [installing JavaScript SDK page](https://docs.ditto.live/javascript-installing) and the [Node.js Task App Quickstart](https://docs.ditto.live/javascript-nodejs-quickstart) says that we support Node.js 14 but we don't.

**Expected behavior**

The pages should either contain updated information or, even better, link to a central place where the currently supported Node.js versions are documented. I noticed that the [compatibility with JavaScript](https://docs.ditto.live/compatibility-with-javascript) page contains information about supported operating system versions so I would suggest it to also get a section about supported Node.js versions. 

The JS SDK is supporting Node.js active and maintenance LTS releases according to the [Node.js release schedule](https://github.com/nodejs/release#release-schedule), which is currently (Nov 2023) v18 and v20. Anything below that is not supported, e.g. v14 is not supported.

**Screenshots**
<img width="1178" alt="image" src="https://github.com/getditto/docs/assets/123380273/eb1a0cd3-13b8-46a1-818c-0f740a95d570">

**Comment by contenuto** [comment]
Fixed.
