### ISSUE TITLE
iOS Installing | Both Bluetooth Background Capabilities Need to be Checked

### ISSUE THREAD

**Issue by kndoshn** [getditto/docs#725]
## **The issue**

The iOS Installing doc suggests selecting only one Bluetooth background capability. 
> From Background Modes, click to select Uses Bluetooth LE accessories from the list.

However, we need to also select `Acts as a Bluetooth LE accessories` as Tom answered in Slack.

The fix for this issue has high priority since all new customers would make this mistake.

***
## **Contexts**
Slack: https://dittolive.slack.com/archives/CGHCRFK2L/p1701285751831199?thread_ts=1701262197.192979&cid=CGHCRFK2L

> Yes they should both be checked

> Since they're background modes they're not required for BLE to function, but having them enabled gives us the possibility of sync when the user is in a different app or the phone is locked.

**Comment by contenuto** [comment]
Fixed.
