### ISSUE TITLE
Missing example for legacy API

### ISSUE THREAD

**Issue by pvditto** [getditto/docs#726]
<img width="1260" alt="image" src="https://github.com/getditto/docs/assets/123380273/5534c3a3-9003-4b54-b23c-8ff86bd5c384">

https://app.archbee.com/public/PREVIEW-cYi_Y9BPUkzSpc2leIwaB/PREVIEW-GSo3UftbmYRsNtYSLayyC#C6gJr

That example should be

```js
await ditto.store
  .collection('cars')
  .find('color == "blue"')
  .update((documents) => {
    for (const document of documents) {
      document.color = 'red'
    }
  })
```

**Comment by contenuto** [comment]
Ty
