### ISSUE TITLE
Remove JSON Web Token section

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#730]
**Describe the issue**

JSON Web Token section in the HTTP API is deprecated and the engineering team wants us to remove it from the docs.

Specifically the section that starts with "There are specific cases where a broad, long-lived HTTP API key is not the right authorization mechanism. "

**To Reproduce**

https://docs.ditto.live/authorization#yCsO6

**Additional context**
https://dittolive.slack.com/archives/C0493F7124C/p1701396884587629?thread_ts=1701211059.978369&cid=C0493F7124C

**Comment by contenuto** [comment]
Removed and updated intro as appropriate.
