### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by anyercastillo** [getditto/docs#740]
**Describe the issue**
A link to the legacy documentation is broken

**To Reproduce**
1. Docs site link https://docs.ditto.live/v4-4/faqs#PZJBE
2. Scroll down to section "Legacy Documentation" https://docs.ditto.live/v4-4/faqs#I2oVk
3. Click the legacy documentation link

**Expected behavior**
User should be able to see the legacy documentation

**Screenshots**
![Screenshot 2023-12-18 at 3 22 46 PM](https://github.com/getditto/docs/assets/5747647/d075c34d-4558-4203-8c62-0d7cb8996f62)

**Additional context**

**Comment by contenuto** [comment]
Skyler is decommissioning (not renewing certs) legacy docs.
