### ISSUE TITLE
V4.6 Docs Release (Tentative Feb 21)

### ISSUE THREAD

**Issue by skylerjokiel** [getditto/docs#749]
We are tentatively aiming to release v4.6 of the SDKs on Feb 21. 

- [x] Generate new Versioned page
- [ ] Attachments docs re-write
- [ ] Update API Links
- [ ] Release Notes

**Comment by skylerjokiel** [comment]
@contenuto , as part of this release we will have a collection of updates to the Attachments APIs that we will need to include.

I'll be on point for the first crack at these. https://dittolive.slack.com/archives/CGDF7RN3C/p1706086691094729

**Comment by skylerjokiel** [comment]
https://app.archbee.com/docs/Ne9YHFvQRQ5_Vz7N00yd6/OvcYk8TV89mLwivT7Ykk7#6S0lJ

**Comment by contenuto** [comment]
Shipped!
