### ISSUE TITLE
Managing Ditto as a Singleton

### ISSUE THREAD

**Issue by mbalex99** [getditto/docs#90]
Typically a UI application should use Ditto as a singleton instance. If a ditto instance goes out of scope, syncing will stop. 

# Solution

Create a Quick TIps section that details suggestions about managing a Ditto instance. 

- [ ] Android: #404 
- [ ] Swift: Managing ditto as a singleton

**Comment by okdistribute** [comment]
Instead of having this in the Quick Tips section, I think we should instead put this into the Installation or Tutorial for each language.

**Comment by contenuto** [comment]
Confirmed recommendation for singleton instance with global scope is included in docs.
